### ISSUE TITLE
Vue placholder doesn't work in Styleguide-VueUsage-Sitecore-Placeholder Component. 

### ISSUE THREAD

**Issue by bdruziuk** [exdst/jss-astro-public#23]
Error appears when Vue component added to "vue" placeholder on "Styleguide-VueUsage-Sitecore-Placeholder" 
![image](https://github.com/exdst/jss-astro-public/assets/4252404/4efe61e8-471b-48de-b657-af8b6e731197)

**Comment by Antonytm** [comment]
Fixed in a3a7bd79cec92affb2d3a01fcbca9a3be7a9a40f
